using System.ComponentModel.DataAnnotations;

namespace DotNetCoreMVC_MakerChecker.Models
{
    public class Employee
    {        
            [Key]
            public int EmployeeId { get; set; }

            public int EmpCode { get; set; } // Autogenerated EmpCode

            [Required]
            public string? Name { get; set; }

            //[Required]
            //[StringLength(10)]
            //public string PhoneNo { get; set; }


            [Required]
            [Phone] // Adds phone number validation
            [StringLength(10, MinimumLength = 10, ErrorMessage = "Phone number must be 10 digits long.")]
            public string PhoneNo { get; set; }


            //[Required]
            //public DateTime DOB { get; set; }

            public string? Dept { get; set; }

            public string? Status { get; set; }

            public string? RejectReason { get; set; }

            public int? LoggedUserId { get; set; }

        }
    }

